AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
#Need to upload zip to S3 first 
  InputTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: 'd9-findings'
      TopicName: 'd9-findings'
  InputTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: D9DeliveryPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: D9DeliveryPolicy
          Effect: Allow
          Principal:
            AWS: 'arn:aws:iam::634729597623:root'
          Action: sns:Publish
          Resource: !Ref InputTopic
      Topics:
      - !Ref InputTopic

  OutputTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: 'remediationOutput'
      TopicName: 'remediationOutput'
  RemediationFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: dome9AutoRemediations
      Description: 'Auto-remediation actions from Dome9 events'
      CodeUri: ./remediation-function.zip
      Runtime: python3.6
      Timeout: 120 # Most will be under 8 seconds, but delete IGW needs to wait for the instances to be off before detaching from the VPC. This takes a bunch of time. 
      Handler: index.lambda_handler
      Policies:
       - Version: '2012-10-17' # Custom Policy Document
         Statement:
           - Effect: Allow
             Action:
               - S3:GetObject
               - sns:Publish # For exporting the logs from CS2 
               - sts:GetCallerIdentity # For checking what account this is running in
               - ec2:TerminateInstances
               - ec2:StopInstances
               - ec2:CreateTags
               - ec2:CreateSecurityGroup # For instance_quarantine
               - ec2:CreateFlowLogs # For vpc_turn_on_flow_logs
               - ec2:MonitorInstances # For ec2_enable_detailed_monitoring
               - ec2:ModifyImageAttribute # For instance_quarantine
               - ec2:DeleteSecurityGroup # For sg_delete
               - ec2:DescribeSecurityGroups # For instance_quarantine
               - ec2:RevokeSecurityGroupEgress # For sg_rules_delete
               - ec2:RevokeSecurityGroupIngress # For sg_rules_delete
               - s3:DeleteBucket # For s3_delete_bucket
               - s3:GetBucketPolicy
               - s3:DeleteBucketPolicy
               - s3:GetBucketAcl
               - s3:PutBucketAcl
               - s3:PutBucketLogging # For s3_enable_logging
               - s3:PutEncryptionConfiguration # For s3_enable_encryption
               - iam:CreatePolicy
               - iam:GetPolicy
               - iam:AttachRolePolicy
               - iam:CreateRole # For vpc_turn_on_flow_logs
               - iam:UpdateAccountPasswordPolicy # For IAM_turn_on_password_policy
               - iam:AttachUserPolicy # For iam_quarantine_user
               - iam:PassRole # Effective 28 April, 2018, AWS users who call CreateFlowLogs will be required to have the IAM PassRole permission[1].
               - s3:PutObject # For create_cloudtrail
               - s3:PutBucketPolicy # For create_cloudtrail
               - s3:CreateBucket # For create_cloudtrail
               - cloudtrail:CreateTrail # For create_cloudtrail
               - cloudtrail:StartLogging # For create_cloudtrail
             Resource: '*'
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref OutputTopic
      Events:
        d9Findings:
          Type: SNS
          Properties:
            Topic: !Ref InputTopic
Outputs:
  InputTopicARN:
    Description: 'ARN that Dome9 sends events to'
    Value: !Ref InputTopic
  OutputTopicARN:
    Description: 'ARN for the export logs topic'
    Value: !Ref OutputTopic


