AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
#Need to upload zip to S3 first 
  InputTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: 'd9Events'
      TopicName: 'd9Events'
  InputTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: D9DeliveryPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: D9DeliveryPolicy
          Effect: Allow
          Principal:
            AWS: 'arn:aws:iam::634729597623:root'
          Action: sns:Publish
          Resource: !Ref InputTopic
      Topics:
      - !Ref InputTopic

  OutputTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: 'remediationOutput'
      TopicName: 'remediationOutput'
  RemediationFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: dome9AutoRemediations
      Description: 'Auto-remediation actions from Dome9 events'
      CodeUri: s3://<YOUR-BUCKET-NAME>/remediation-function.zip
      Runtime: python3.6
      Handler: index.lambda_handler
      Policies:
       - Version: '2012-10-17' # Custom Policy Document
         Statement:
           - Effect: Allow
             Action:
               - S3:GetObject
               - sns:Publish
               - sts:GetCallerIdentity
               - ec2:TerminateInstances
               - ec2:StopInstances
               - ec2:CreateTags
               - ec2:DeleteSecurityGroup
               - ec2:DescribeSecurityGroups
               - ec2:RevokeSecurityGroupEgress
               - ec2:RevokeSecurityGroupIngress
               - s3:DeleteBucket
               - s3:GetBucketPolicy
               - s3:DeleteBucketPolicy
               - s3:GetBucketAcl
               - s3:PutBucketAcl
               - iam:CreatePolicy
               - iam:GetPolicy
               - iam:AttachRolePolicy
               - iam:AddUserToGroup

             Resource: '*'
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref OutputTopic
      Events:
        d9Event:
          Type: SNS
          Properties:
            Topic: !Ref InputTopic
Outputs:
  InputTopicARN:
    Description: 'ARN that Dome9 needs to send events to'
    Value: !Ref InputTopic
  OutputTopicARN:
    Description: 'ARN that the function will export logs to'
    Value: !Ref OutputTopic


